version: '3'
services:
  telemonitor:
    image: ghcr.io/bboysoulcn/telemonitor:latest
    restart: always
    container_name: telemonitor
    environment:
      - TG_CHAT_ID=your_chat_id
      - TG_API_TOKEN=your_api_token
      - CPU_PERCENT=80
      - MEMORY_PERCENT=80
      - DISK_PERCENT=80
      - MONITOR_INTERVAL=300
      - TG_API_BASE_URL=https://api.telegram.org/bot
      - DISK_PATH=/host
      - URL_LIST=https://www.baidu.com,https://www.google.com,https://www.bing.com
      - LANGUAGE=cn
    network_mode: host
    pid: host
    volumes:
      - /etc/localtime:/etc/localtime
      - /:/host:ro